### ISSUE TITLE
Python - Server Synchronisation

### ISSUE THREAD

**Issue by Loeffler13** [TeamA1-SPM/Python-Client-Racer#3]
#2 

- [ ] get road from server
- [ ] game activated by server countdown
- [ ] draw enemy car #6
- [ ] synchronize NPC cars #2 
- [ ] end game screen #10
- [ ] spielernamen #6  
- [ ] highscore list #3
